Add sq, cq, resources for queue and regex_dev, enqueue and dequeue functionalities and test
Mellanox/regex pull request #22
Opened 2020-02-14 22:49 UTC by vuhuong

This PR includes:
+ Add CQ create, destroy and arm helper APIs
+ Add SQ create and destroy helper APIs
+ Implement QP create callback
+ Add device and queue resources for enqueue dequeue
+ Add and enable enqueue and dequeue functions
+ Add test regex appliacation

2020-02-18 07:35 UTC, orikam requested changes
I will review more later

2020-02-18 07:35 UTC, orikam commented on drivers/regex/mlx5/mlx5_regex_queue.c
> +	seg->mmo_control_31_0 = htobe32(mmo_control_31_0);
should be changed to rte_cpu_to_be_32
same for all 3 lines

2020-02-18 07:35 UTC, orikam commented on drivers/regex/mlx5/mlx5_regex_queue.c
> +			    lkey, job->m_iov.buf_iova);
we should create those function in DPDK.
buf_iova should be changed to buf addr

2020-03-18 23:22 UTC, yuvalavn commented on drivers/regex/mlx5/mlx5_regex_queue.c
> +	q->sq.db_rec[MLX5_SND_DBR] = rte_cpu_to_be_32(q->sq.pi & MLX5_QP_CI_MASK);
Hi vu
this a bug
please see PRM
need to be the next empty wqbb and not wqe index

2020-03-18 23:42 UTC, yuvalavn commented on drivers/regex/mlx5/mlx5_regex_queue.c
> +	*(uint32_t *)q->sq.db_addr = *(uint64_t *)cseg;
Every write need to be alternated between odd and even on the uar
please see PARM

2020-03-18 23:53 UTC, yuvalavn commented on drivers/regex/mlx5/mlx5_regex_queue.c
> +	*(uint64_t *)q->sq.db_addr = *(uint64_t *)cseg;
We should use blueflame for performance
It means writing the whole wqe to the BAR not just the ctrl segment

2020-03-18 23:53 UTC, yuvalavn commented on drivers/regex/mlx5/mlx5_regex_queue.c
> +	*(uint32_t *)q->sq.db_addr = *(uint64_t *)cseg;
this comment relates to blueflame

2020-03-19 00:36 UTC, yuvalavn requested changes

2020-03-19 00:36 UTC, yuvalavn commented on drivers/regex/mlx5/mlx5_regex_queue.c
> +	*(uint64_t *)q->sq.db_addr = *(uint64_t *)cseg;
Should be
*(volatile uint64_t *)cseg;

2020-07-02 19:51 UTC, closed without merging